<template>
  <div class="prose prose-slate max-w-none">
    <h1>Terms of Use</h1>
    <p class="text-sm text-muted-foreground">Last updated: June 2026</p>

    <h2>1. Acceptance of Terms</h2>
    <p>
      By accessing The Neural Journal (theneuraljournal.com), you agree to these Terms of Use.
      If you do not agree, please discontinue use of the site.
    </p>

    <h2>2. Content Disclaimer</h2>
    <p>
      Articles on The Neural Journal are generated by artificial intelligence based on
      publicly available news sources. While we employ quality gates and source
      verification, AI-generated content may contain errors, omissions, or
      misinterpretations. <strong>We do not guarantee the accuracy, completeness,
      or timeliness of any article.</strong> Content is provided for informational
      purposes only and does not constitute professional advice.
    </p>

    <h2>3. Intellectual Property</h2>
    <p>
      Article text generated by our AI engine is published under a
      Creative Commons Attribution 4.0 International License (CC BY 4.0).
      You may share and adapt our content with appropriate attribution.
      Source material referenced in articles remains the property of the
      original publishers. Our site name, logo, and design elements are
      proprietary and may not be used without permission.
    </p>

    <h2>4. User Conduct</h2>
    <p>
      The Neural Journal is a read-only publication. There are no user accounts,
      comments, or submission features for the general public. Accessing the
      site through automated means that degrade service for other users is
      prohibited.
    </p>

    <h2>5. Third-Party Links</h2>
    <p>
      Articles contain links to original source material hosted by third-party
      publishers. We are not responsible for the content, accuracy, or
      availability of external sites.
    </p>

    <h2>6. Limitation of Liability</h2>
    <p>
      The Neural Journal and its operators shall not be liable for any damages
      arising from the use of, or reliance on, content published on this site.
    </p>

    <h2>7. Changes to Terms</h2>
    <p>
      We may revise these terms at any time. Continued use of the site after
      changes constitutes acceptance of the revised terms.
    </p>

    <h2>8. Contact</h2>
    <p>
      For legal inquiries, contact
      <a href="mailto:hello@theneuraljournal.com">hello@theneuraljournal.com</a>.
    </p>
  </div>
</template>

<script setup lang="ts">
useHead({ title: 'Terms of Use — The Neural Journal' })
</script>
